language: c
os: osx
osx_image: xcode9.2

before_install:
 - brew update
 - brew install cctools
 - ln -s /usr/local/Cellar/cctools/855/efi/bin/mtoc /usr/local/bin/mtoc
 - brew install nasm

install:
 - cd $TRAVIS_BUILD_DIR/../
 - git clone https://github.com/tianocore/edk2
 - cd edk2
 - make -C BaseTools -s -j 6
 - source edksetup.sh
 - cd $TRAVIS_BUILD_DIR
 - export PACKAGES_PATH=$TRAVIS_BUILD_DIR/../

script:
 - ./gen-version.sh XCODE5
 - build -p Clover/Clover.dsc -a IA32 -b RELEASE -t XCODE5 -n 6
 - build -p Clover/Clover.dsc -a X64 -b RELEASE -t XCODE5 -n 6
